document.write('<style type="text/css">\n');
document.write('.upgotd { color: #7b7670; font-family: sans-serif; }\n');
document.write('.upgotd-box { background-color: #ffffff; text-align: center; width: 215px;  font-size: 12px;}\n');
document.write('.upgotd-box a { color: #7b7670 !important; text-decoration: none; }\n');
document.write('.upgotd-box a:hover { color: #ed7c31 !important; text-decoration: none; }\n');
document.write('.upgotd-title, { text-transform:uppercase; background-color: #42ad9e; font-family:sans-serif; font-weight: bold; color: #7b7670 !important;  font-size:14px !important; margin-bottom: 7px; }\n');
document.write('.upgotd-title a {text-transform:uppercase; background-color: #42ad9e; font-family:sans-serif; font-weight: normal; color: #f8f7f3 !important; font-size:14px !important; margin-bottom: 7px; }\n');
document.write('.upgotd-image { text-align: center; }\n');
document.write('.upgotd-pray { font-weight: normal; padding: 0px; font-size: 9px;}\n');
document.write('.upgotd-people { font-weight: normal; font-size:12px !important; padding-bottom:2px; }\n');
document.write('.upgotd-people a { color: #ed7c31 !important; font-size: 15px; font-family:sans-serif; font-weight: 800; }\n');
document.write('.upgotd-table { margin-bottom: 5px; text-align: left; }\n');
document.write('.upgotd-table tr { border:none; text-align: left;}\n');
document.write('.upgotd-table td { background-color:#ffffff; font-family: sans-serif; font-size:11.5px; font-weight: normal; color: #7b7670; line-height: 12px; text-align: left; border: 0px;  margin: 0px; padding: 0px 0px 0px 5px; line-height: 18px; }\n');
document.write('.upgotd-footer, .upgotd-footer a { color: #ed7c31 !important; font-weight: normal ;font-size: 13px; }\n');
document.write('.upgotd-cite, .upgotd-cite a { color: #7b7670 !important; font-weight: normal ;font-size: 10px;  }\n');
document.write('.upgotd-logo {padding: 0px 2px 4px 2px; width: 22px; height: 20px; }\n');
document.write('</style>\n');
document.write('<div class="upgotd-box">\n');
document.write('<div class="upgotd upgotd-title">\n<a href="http://joshuaproject.net/pray/unreachedoftheday" class="upgotd-link" target="_blank" title="A ministry of Joshua Project\"><img class="upgotd-logo" src="http://joshuaproject.net/assets/img/jp_logo_light_gray_SMALL.png"/> Unreached of the Day</a>\n</div>\n\n');
document.write('<div class="upgotd-image"><a href="http://joshuaproject.net/people_groups/13445/ID" class="upgotd-link" title="Click for a full profile of the Kutai of Indonesia" target="_blank"><img src="http://joshuaproject.net/assets/media/profiles/photos/p13445.jpg" border="0" width="130" height="186"></a>\n</div>\n\n');
document.write('<div class="upgotd upgotd-pray">Please pray for the</div>\n\n');
document.write('<div class="upgotd upgotd-people">\n<a href="http://joshuaproject.net/people_groups/13445" class="upgotd-link" title="Click for a listing of this people group in all countries" target="_blank">Kutai</a> in <a href="http://joshuaproject.net/countries/ID" class="upgotd-link" title="Click for a listing of all people groups in this country" target="_blank">Indonesia</a>\n</div>\n');
document.write('<table align="center" class="upgotd-table" cellpadding="0" cellspacing="0">');
document.write('<tr>\n<td width="65">Population:</td>\n    <td width="135" class="upgotd-stats">246,000</td>\n</tr>\n');
document.write('<tr>\n<td>Language:</td>\n<td>Malay, Tenggarong Kutai</td>\n</tr>\n');
document.write('<tr>\n<td>Religion:</td>\n<td>Islam</td>\n</tr>\n');
document.write('<tr>\n<td>Evangelical:</td>\n<td>0.04%</td>\n</tr>\n');
document.write('<tr>\n<td>Status:</td>\n<td><a href="http://joshuaproject.net/help/definitions#Unreached-Least-Reached"  class="upgotd-link"  title="Click for a definition of unreached" target="_blank">Unreached</a>&nbsp;&nbsp;<a href="http://joshuaproject.net/help/definitions#Progress-Scale" class="upgotd-link" title="Click for a description of the Joshua Project Progress Scale" target="_blank"><img src="http://joshuaproject.net/assets/img/scale/scale1round.png" style="padding-top: 4px"; border="0"></a></td>\n</tr>');
document.write('</table>\n');
document.write('<div class="upgotd upgotd-footer">\n<a href="http://joshuaproject.net/pray/unreachedoftheday#subscribe" title="Get the complete Unreached People of the Day profile by daily email" target="_blank"><b>Subscribe</b></a>\n&nbsp;&nbsp;\n<a href="http://joshuaproject.net/pray/unreachedoftheday#Widget" title="Add this widget to your website"  target="_blank"><b>Add to Website</b></a>\n');
document.write('<div class="upgotd upgotd-cite">Provided by <a href="http://joshuaproject.net">Joshua Project</a>\n</div>\n');
document.write('</div>\n');
document.write('</div>\n');